from itertools import product

from yoshix.yoshiegg import YoshiEgg, YoshiEggKeyException


class YoshiExperiment(object):
    """
    `YoshiExperiment` is the base class for every user created experiment.

    The class provide the basic interface and infrastructure to register data,
    run single experiments, generate input data and so on.

    The class should never be initialized by its own. This should be always
    extended by a child class.
    """

    def __init__(self):
        self.name = self.__class__.__name__
        self._generators = {}
        self.__egg = None
        self._egg_is_ready = False  # Egg is ready only after the experiment.
        self.__empty_row = None
        self.__run_counter = 0
        self.__fixed_parameters = {}
        self.__generators_iterator = None


    def setup(self):
        """
        This function is called before the experiment is started. This can be
        used to initialize variables, generators and every other detail.
        :return: None
        """
        pass

    def single_run(self, params):
        """
        This represent the atomic experiment run.
        :param params List of parameters for the experiment run. This is automatically
        generated by the parent method.
        :return: None
        """
        pass

    def _run_experiment(self):
        """
        The wrapping experiment loop. This function invokes single_run for
        every combination of **variable parameters** provided by the generators.
        :return: None
        """
        self.__run_counter = 0
        while True:  # TODO: Is there a better way to iterate until the Iterator is empty?
            try:
                self.__egg.add_row(self.__empty_row)
                self.__run_counter += 1

                # Generating Parameters dictionary
                params = self.__fixed_parameters.copy()
                params.update(self.__generate())

                self.single_run(params)
            except StopIteration:
                break
        self._egg_is_ready = True

    def after_run(self):
        """
        This method is invoked after the experiment is completed.

        Can be used to package the result Egg, clean up the disk and more.
        :return:
        """
        pass

    @property
    def partial_egg(self):
        if self.__egg is None:
            raise EggNotReady("Try to access an egg that is None")
        else:
            return self.__egg

    @property
    def egg(self):
        if self._egg_is_ready:
            return self.__egg
        if self.__egg is None:
            raise EggNotReady("Try to access an egg that is None")
        elif not self._egg_is_ready:
            raise EggNotReady("The egg is there but the experiment is not completed yet!")
        else:
            raise Exception("Something is really wrong there!")

    @property
    def run_counter(self):
        return self.__run_counter

    def setup_egg(self, data_headers, row_initialization=None):
        self.__egg = YoshiEgg(data_headers)
        # If row_init is None we assume all zeroes.
        if row_initialization is None:
            row_initialization = tuple((0 for _ in data_headers))
        if len(row_initialization) == len(data_headers):
            self.__empty_row = row_initialization
        else:
            raise YoshiEggKeyException("Initialization vector does not match the header.")

    def assign_generators(self, key, generator):
        if key not in self.__egg:
            raise YoshiEggKeyException("It is not possible to attach a generator to an unknown key!")
        self._generators[key] = generator
        gen_list = [v for _, v in self._generators.items()]
        self.__generators_iterator = product(*gen_list)

    def assign_fixed_parameter(self, key, value):
        if key not in self.__egg:
            raise YoshiEggKeyException("It is not possible to attach a value to an unknown key!")
        self.__fixed_parameters[key] = value

    def __generate(self):
        if self.__generators_iterator is not None:
            current_iteration = next(self.__generators_iterator)
            return {k: v for k, v in zip(self._generators.keys(), current_iteration)}


class EggNotReady(Exception):
    pass
